#!/bin/bash

set -eou pipefail

get_meta() {
  buildkite-agent meta-data get $@
}

export targetdevice=`get_meta targetdevice`
export Changelog=`get_meta changelog`

echo "Target device: $targetdevice"
echo "Changelog: $Changelog"

if [ -z "$targetdevice" ]; then
	echo "Target device not defined!"
	exit 1
fi

./build.run

