version: "3.7"

services:
  buildkite:
    build: .
    restart: unless-stopped
    environment:
      KEYS_FILE: ${KEYS_FILE:-}
    volumes:
      - /etc/hostname:/etc/machine-id:ro
      - ./buildkite-agent.cfg:/etc/buildkite-agent/buildkite-agent.cfg:ro
      - ./credentials:/etc/buildkite-agent/credentials:ro
      - ./hooks:/etc/buildkite-agent/hooks:ro
      - ${BUILDKITE_DIR}:/bk
      - ${BUILDKITE_CCACHE_DIR}:/ccache
      - ${BUILDKITE_KEYS_DIR:-./keys}:/keys

